version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk 
    steps:
      - run:
          name: The First Step
          command: |
            ls -alh 
            mkdir build
            ls -alh 
            cd build
            sudo apt-get install python*
            sudo apt-get install python3-dist*
            sudo apt-get install git
            sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libssl-dev
            sudo apt-get update
            git clone -b yocto-2.4.3 --depth 1 git://git.yoctoproject.org/poky &
            git clone -b rocko --depth 1 git://git.linaro.org/openembedded/meta-linaro.git &
            git clone -b rocko --depth 1 git://git.openembedded.org/meta-openembedded &
            wait
            ls -alh
            source poky/oe-init-build-env
            bitbake core-image-minimal
