version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:latest 
    steps:
      - run:
          name: The First Step
          command: |
            mkdir build
            cd build
            
            sudo apt-get update
            sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm cpio python3 python3-pip python3-pexpect xz-utils debianutils python iputils-ping libssl-dev
            
            sudo apt-get install locales
            git clone -b yocto-2.4.3 --depth 1 git://git.yoctoproject.org/poky &
            git clone -b rocko --depth 1 git://git.linaro.org/openembedded/meta-linaro.git &
            git clone -b rocko --depth 1 git://git.openembedded.org/meta-openembedded &
            wait
            sudo update-alternatives --install /usr/local/bin/python python /usr/bin/python2.7 1       
    
            source poky/oe-init-build-env
            echo "Bitbake start"
            echo "Test Start"
            locale -a 
            sudo locale-gen en_US
            sudo locale-gen en_US.UTF-8
            sudo apt-get install language-pack-en
            
            sudo dpkg-reconfigure locales
            echo "Test End"
           
            bitbake core-image-minimal
