version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01 
    steps:
      - run:
          name: The First Step
          command: |
            ls -alh 
            mkdir build
            ls -alh 
            cd build
            sudo apt-get install python
            sudo apt-get install python3-dist*
            sudo apt-get install git
            git clone -b yocto-2.4.3 --depth 1 git://git.yoctoproject.org/poky &
            git clone -b rocko --depth 1 git://git.linaro.org/openembedded/meta-linaro.git &
            git clone -b rocko --depth 1 git://git.openembedded.org/meta-openembedded &
            wait
            ls -alh
            source poky/oe-init-build-env
            bitbake core-image-minimal
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
