version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            ls -alh ~
            mkdir build


            echo 'Hello World!'
            echo 'This is the delivery pipeline'
