version: 2.1
jobs:
  build:
#    docker:
#      - image: buildpack-deps:trusty
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            sudo apt-get update
            sudo apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat libsdl1.2-dev xterm cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping libssl-dev
            sudo apt-get install locales*
            ls -alh /usr/bin/python*
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
            export PATH=/usr/bin/:$PATH
            which python
            which python3
            cat /etc/issue
            ls -alh
